# See https://pre-commit.com/ for usage and config
fail_fast: true

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ".srt$"
      - id: trailing-whitespace
        exclude: ".srt$|.gresource.xml$"
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: glib
        name: glib-compile-resources
        entry: glib-compile-resources --sourcedir=resources --target=myhumbleself/resources/myhumbleself.gresource resources/myhumbleself.gresource.xml
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        stages: [commit]
        language: system
        entry: ruff check --fix .
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        stages: [commit]
        language: system
        entry: ruff format .
        pass_filenames: false
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: mypy
        pass_filenames: false
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        pass_filenames: false
      - id: pydeps
        name: pydeps
        stages: [commit]
        language: system
        entry: pydeps myhumbleself --max-bacon=2 -o=pydeps.png -T=png
        pass_filenames: false
      - id: code2flow
        name: code2flow
        stages: [commit]
        language: system
        entry: code2flow myhumbleself --no-trimming --exclude-function=(global) --output=code2flow.png
        pass_filenames: false
