blank_issues_enabled: true
contact_links:
  - name: Blank issue
    url: https://github.com/dynobo/myhumbleself/issues/new
    about: Use this if non of the above seem fitting.
  - name: Discussions & Feedback
    url: https://github.com/dynobo/myhumbleself/discussions/categories/q-a
    about: Please ask general questions in the forum.
