name: "coverage.io"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-3-dev
      - name: Install python deps
        run: pip install '.[dev]'
      - name: Run tests
        run: pytest -m "gui or not gui"
      - name: Coveralls
        uses: coverallsapp/github-action@v2
