name: Test
on: [push, pull_request]

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on Linux64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-4-dev \
             libxml2-utils `# required for pre-commit hooks`
      - name: Install python deps
        run: pip install '.[dev]'
      - name: Run tests
        run: pre-commit run --all-files
      - name: Run GUI tests
        run: pytest -m gui

  publish:
    name: Build & Publish
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
             libgirepository1.0-dev \
             libcairo2-dev \
             python3-gi \
             gobject-introspection \
             libgtk-4-dev
      - name: Install python deps
        run: pip install '.[dev]'
      - name: Build
        run: python -m build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      - uses: ncipollo/release-action@v1
        with:
          body: See [CHANGELOG.md](https://github.com/dynobo/myhumbleself/blob/main/CHANGELOG.md) for details.
